language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
env:
install: composer install
addons:
  code_climate:
    repo_token: a2bd599d6b818c89d627730abf660dbb78809acd20f78da3c0b28cfa3493b101
after_script:
    - vendor/bin/test-reporter


